### ISSUE TITLE
极速版不能领红包

### ISSUE THREAD

**Issue by BlueHtml** [asd920/Auto#88]
极速版不能领红包了吗？试了下手动进去是可以领的

**Comment by asd920** [comment]
> 极速版不能领红包了吗？试了下手动进去是可以领的

目前黑号几率大，所以禁用了

**Comment by BlueHtml** [comment]
> > 极速版不能领红包了吗？试了下手动进去是可以领的
> 
> 目前黑号几率大，所以禁用了

好的，感谢回复
