### ISSUE TITLE
种豆得豆报错

### ISSUE THREAD

**Issue by BlueHtml** [asd920/Auto#90]
```
【浏览店铺】任务未完成,关注店铺随机可得1瓶营养液

开始做 浏览店铺任务

❗️京东种豆得豆, 错误!
TypeError: goodShopList is not iterable
    at doTask (E:\Auto\jd_plantBean.js:266:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async jdPlantBean (E:\Auto\jd_plantBean.js:117:7)
    at async E:\Auto\jd_plantBean.js:75:7
```

**Comment by asd920** [comment]
> ```
> 【浏览店铺】任务未完成,关注店铺随机可得1瓶营养液
> 
> 开始做 浏览店铺任务
> 
> ❗️京东种豆得豆, 错误!
> TypeError: goodShopList is not iterable
>     at doTask (E:\Auto\jd_plantBean.js:266:23)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async jdPlantBean (E:\Auto\jd_plantBean.js:117:7)
>     at async E:\Auto\jd_plantBean.js:75:7
> ```

已修复

**Comment by BlueHtml** [comment]
现在好了，谢谢
